dell/gopowerscale

.github/CODEOWNERS, .github/pull_request_template.md, .github/workflows/actions.yml
Added github actions yaml file
Added code owners file.
=> Add github actions and codeowners file

.github/workflows/actions.yml
| |
Removed the forbidden word check..
=> Remove forbidden word check and add code-check

api/api.go, api/api_logging.go
=> Logging improvement

api/v1/api_v1_snapshots.go, snapshots.go
The changes allow volume creation from source(snapshot) with different isi path/access zones
=> Pvc from source with different isi paths

README.md, api/api.go, api/api_logging.go
| https://github.com/dell/csm/issues/139|
Updated error condition for authType, It will set to default value 0 if any wrong value is given in values.yaml
Updated logs for masking basic auth creds
=> Updated error condition for authType and imporved logging for basic auth

go.mod
|https://github.com/dell/csm/issues/171 |
Updated golang version to 1.17
=> Golang version update

api/api_logging.go
| https://github.com/dell/csm/issues/139|
Earlier in Basic auth logs, everything was commented now only password will be commented while for session-based auth everything remains the same.
Added a separate if condition for basic auth logs such that only username is visible and password is masked in the logs
the else part is valid for session-based auth which masks the password, cookie, X-CSRF token in logs.
**Basic auth logs:**
GET /platform/3/cluster/config/ HTTP/1.1
Host: 1.2.3.4:8080
Authorization: root:******
**Session-based auth logs:**
GET /platform/3/cluster/config/ HTTP/1.1
Host: 1.2.3.4:8080
Cookie: isisessid=****-6121-4619-928a-8327b5054266
Referer: https://1.2.3.4:8080 …
=> logs updated for basic auth

api/v3/api_v3_cluster.go, api/v3/api_v3_types.go, cluster.go
| https://github.com/dell/csm/issues/262 |
Added a method IsIOinProgress() which gives the list of current nodes doing IO currently with the array.
=> Resiliency changes for gopowerscale

go.mod, go.sum
| https://github.com/dell/csm/issues/243 |
Updated yaml dependency version to fix dependabot alert and ran cert-csi tests to verify.
=> Depenedabot alert fixed for goisilon

api/v1/api_v1_quotas.go, api/v1/api_v1_types.go, api/v3/api_v3_cluster.go, api/v3/api_v3_types.go, cluster.go, cluster_test.go, quota.go, quota_test.go
| https://github.com/dell/csm/issues/340 |
Add getting all quotas API 
Add cluster API for querying float type stats
=> Enhance api for getting quotas and float stats

.github/CODEOWNERS
Adding the name in the CODEOWNER file in the github for gopowerscale
| https://github.com/dell/csm/issues/350|
<your change goes here>
=> adding Harish H and Meghana name

README.md
README update
|https://github.com/dell/csm/issues/350|
README update with latest csm support channel
=> support links updated

client.go, env.sh, exports.go, goisilon_test.go, replication.go, replication_test.go, volume.go, volume_test.go
|https://github.com/dell/csm/issues/491|
Update Copyright information.
=> Update Copyright information

api/v1/api_v1_quotas.go, api/v1/api_v1_types.go, quota.go
Quota limit Changes 
|https://github.com/dell/csm/issues/742 |
Added following parameter support in quota creation and corresponding API calls
- Soft limit 
- advisory limit 
- soft grace period
=> Quota limit changes

api/v1/api_v1_quotas.go
|https://github.com/dell/csm/issues/742 |
Removed name from comments .
=> removed name from comment

api/v1/api_v1_snapshots.go, api/v1/api_v1_types.go, snapshots.go
Error Handing for PVC Creation from Copysnapshot
| https://github.com/dell/csm/issues/749|
Taken the Response from the OneFS, checking the weather response as success state as false, which means copy snapshot is failed. and collecting error messages from response JSON 
In Failed case
In Success Case
=> Error Handling for pvc creation from copysnapshot

api/v1/api_v1_quotas.go, api/v11/api_v11_replication.go, env.sh, exports_test.go, goisilon_test.go, replication.go, replication_test.go
| https://github.com/dell/csm/issues/753 |
Merging 1.11.1 changes from PR https://github.com/dell/gopowerscale/pull/39 to main branch.
=> Fix query quota call by path (#39) to main branch

.github/workflows/actions.yml
|https://github.com/dell/csm/issues/743 |
Upgrade actions/checkout from v2 to v3.
=> Upgrade actions/checkout to v3

api/v1/api_v1.go, api/v1/api_v1_roles.go, api/v1/api_v1_types.go, api/v1/api_v1_users.go, goisilon_test.go, role.go, role_test.go, user.go, user_test.go
Implement API for user and role to support PowerScale Terraform Provider:
- add CRUD API for user
- add Get API for role
- add add/remove roleMemebr API for role
| https://github.com/dell/csm/issues/888 |
All unit tests for role and user are passed:
```
time="2023-07-05T04:29:59Z" level=debug msg="opts.Insecure : 'true'"
time="2023-07-05T04:29:59Z" level=debug msg="\n    -------------------------- GOISILON HTTP REQUEST -------------------------\n    GET /platform/latest/ HTTP/1.1\n    Host: 10.230.24.249:8080\n    Authorization: root:******\n    \n"
time="2023-07-05T04:30:00Z" level=debug msg="\n    -------------------------- GOISILON HTTP RESPONSE -------------------------\n    HTTP/1.1 200 Ok\n …
```
=> Implement API for user and role

api/api.go
Logic twist to handle UTs 
|https://github.com/dell/csm/issues/1134|
=> parsing html json

.github/workflows/go-version.yaml, acls.go, api/v2/api_v2_acls.go, client.go, goisilon_test.go, role_test.go, snapshots_test.go, user_group_test.go
Add caller workflow Go Version Update. It can be manually triggered or it can be triggered by [Trigger Go Version Workflow](https://github.com/dell/common-github-actions/actions/workflows/trigger-go-workflow.yaml).
| https://github.com/dell/csm/issues/1490 |
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration
=> Add go version update worklow

.github/workflows/release.yaml
| https://github.com/dell/csm/issues/1490 |
Added release automation
=> Added release automation action

api/v11/api_v11_replication.go
| https://github.com/dell/csm/issues/1559 |
Reverted json field name changes made in PR [79](https://github.com/dell/gopowerscale/pull/79)
=> Reverted json field name changes made in PR 79

api/v1/api_v1_test.go, api/v14/api_v14_cluster_test.go, api/v3/api_v3_cluster_test.go, api/v7/api_v7_cluster_test.go
=> UT for v1,v14,v3 and v7 package

api/api.go, api/api_test.go
This PR sets the log level to Debug is the appropriate environment variable is set to `true` in the driver's sample
|https://github.com/dell/csm/issues/1762|
- Enable debug log level according to the environment variable set in the driver's sample
- UT update to respect debug log level
=> Set Debug Log Level

exports.go, exports_test.go
Validation for maximum volumes per node before controller publish
| https://github.com/dell/csm/issues/1896 |
- [ x ] Have you made sure that the code compiles?
- [ x ] Have you commented your code, particularly in hard-to-understand areas
- [ x ] Did you run tests in a real Kubernetes cluster?
- [ x ] Have you maintained backward compatibility
Test :
k8s e2e test successful
CSI sanity test passing
=> Validation for maximum volumes per node before controller publish

.github/workflows/release.yaml
This Commit fixes the issue with Auto-release of the CSM go libraries.
|https://github.com/dell/csm/issues/1490 |
Test A: Tested by forking the repo: https://github.com/meggm/common-github-actions-test/actions/runs/17156566555
=> Fixed the null version during auto-release
